### ISSUE TITLE
Bug: Preview function is not working in production

### ISSUE THREAD

**Issue by vykster** [cal-itp/transit-stop#200]
When logged into production CMS admin interface. The "View Live" link to view a preview gives a "page not found error" in a new tab. 

Example editing this page `https://cal-itp-transit-stop.netlify.app/admin/#/collections/pages/entries/homepage` links to `https://cal-itp-transit-stop.netlify.app/homepage` with error. 

May be a problem with configuration.

**Comment by krainboltgreene** [comment]
So it looks like this bug is specific to the `homepage` page, because the actual url is `/` not `/homepage`. It also looks like deploy preview site's live preview links point to the production page, which doesn't make sense.

**Comment by thekaveman** [comment]
^ @krainboltgreene has it right - last I checked, the preview functionality really only works correctly for collection-based content items like Blog Posts. They may have updated their handling of this since that was back in the fall when I was looking. 

https://www.netlifycms.org/docs/deploy-preview-links/

**Comment by calexity** [comment]
@krainboltgreene @thekaveman - Harrison is reporting that this does not work on any page.

**Steps to reproduce the bug**
1) Draft a blank page
2) Click the preview
3) See that you get the homepage 

**Expected behavior**
See the post you drafter

FWIW I think this is a bug with Netlify because I was able to reproduce on their demo cms

**Comment by calexity** [comment]
https://www.netlifycms.org/docs/deploy-preview-links/ @krainboltgreene
